name: WebRegionAutomator
version: '1.0.0'
main: com.clusters_prj.wra.Main
description: 'Web申請連動型の自動保護プラグイン'
authors:
  - clusters-prj
depend:
  - WorldGuard
  - WorldEdit
softdepend: []

commands: {}
permissions: {}