# BGM Plugin 設定ファイル

# JavaリソースパックのURL（公開HTTPSサーバーに置いたzipのURL）
resource-pack-url: "https://github.com/swmr71/MinecraftKaguya/releases/download/BGM-latest/resourcepack.zip"

# デバッグモード
# true: プラグインフォルダ内の debug.log に詳細なログを出力します。
# false: コンソール（ターミナル）に標準的なログを出力します。
debug: false

# リソースパックのSHA-1ハッシュ（任意だが推奨）
# sha1sum bgm-java.zip で取得できる
resource-pack-sha1: "b6a840056a40e978f59954124fa779afe1e33b83"

# リソースパックの適用を強制するか
force-resource-pack: true

# 音量 (0.0 ~ 1.0)
volume: 1.0

# ピッチ (通常は1.0)
pitch: 1.0

# BGM一覧（ランダムに選ばれる）
# key: sounds.jsonのキーと一致させる
# duration-seconds: 曲の長さ（秒）
sounds:
  - key: "custom.bgm1"
    duration-seconds: 252
  - key: "custom.bgm2"
    duration-seconds: 225
